name: Build windows artifacts and attach to release

on:
  release:
    types: [published]

jobs: 
  build:
    name: Build windows artifacts and attach to release
    runs-on: win11
    permissions:
      contents: write
    env:
      SIGN_TOKEN_ALIAS: ${{ secrets.SIGN_TOKEN_ALIAS }}
      SIGN_TOKEN_PASS: ${{ secrets.SIGN_TOKEN_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
            node-version: 18
            cache: "npm"
      - name: Install dependencies
        run: npm install --package-lock-only; npm ci
      - name: Build
        run: npm run build:win
        env:
          SIGN_TOKEN_ALIAS: ${{ secrets.SIGN_TOKEN_ALIAS }}
          SIGN_TOKEN_PASS: ${{ secrets.SIGN_TOKEN_PASS }}
      - name: Attach artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            prod/filen.exe
            prod/filen.exe.blockmap
            prod/filen_arm64.exe
            prod/filen_arm64.exe.blockmap
            prod/filen_x64.exe
            prod/filen_x64.exe.blockmap
            prod/latest.yml
      - name: Cleanup
        run: npm run clear
      