name: Build artifacts and attach to release

on:
    release:
        types: [published]
    workflow_dispatch:

concurrency:
    group: "build"
    cancel-in-progress: true

jobs:
    buildWindows:
        name: Build windows artifacts and attach to release
        runs-on: windows-latest
        permissions:
            contents: write
        env:
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            ELECTRON_BUILDER_CACHE: "C:\\actions-runner\\cache\\builder"
            ELECTRON_BUILDER_DOWNLOAD_PATH: "C:\\actions-runner\\cache\\electron"
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
            - name: Clear builder cache
              run: |
                  if (Test-Path "$env:ELECTRON_BUILDER_CACHE") {
                    Remove-Item -Recurse -Force "$env:ELECTRON_BUILDER_CACHE"
                  }

                  if (Test-Path "$env:ELECTRON_BUILDER_DOWNLOAD_PATH") {
                    Remove-Item -Recurse -Force "$env:ELECTRON_BUILDER_DOWNLOAD_PATH"
                  }
            - name: Install dependencies
              run: npm ci
            - name: Fetch rclone binaries
              run: node build/rclone/fetch.mjs
            - name: Build
              run: npm run build:win
              env:
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            - name: Generate SHA256 hashes
              run: |
                  Get-ChildItem prod -File | ForEach-Object {
                    $hash = CertUtil -hashfile $_.FullName SHA256 | Select-String -Pattern "^[0-9a-fA-F]{64}$"
                    $hash -replace "\s+", "" | Out-File "$($_.FullName).sha256.txt"
                  }
            - name: Generate update hashes
              run: npm run build:hashes
            - name: Attach artifacts to release
              if: success() && github.event_name == 'release'
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: ${{ github.event.release.tag_name }}
                  files: |
                      prod/Filen_win.exe
                      prod/Filen_win.exe.sha256.txt
                      prod/Filen_win.exe.blockmap
                      prod/Filen_win.exe.blockmap.sha256.txt
                      prod/Filen_win_arm64.exe
                      prod/Filen_win_arm64.exe.sha256.txt
                      prod/Filen_win_arm64.exe.blockmap
                      prod/Filen_win_arm64.exe.blockmap.sha256.txt
                      prod/Filen_win_arm64.zip
                      prod/Filen_win_arm64.zip.sha256.txt
                      prod/Filen_win_x64.exe
                      prod/Filen_win_x64.exe.sha256.txt
                      prod/Filen_win_x64.exe.blockmap
                      prod/Filen_win_x64.exe.blockmap.sha256.txt
                      prod/Filen_win_x64.zip
                      prod/Filen_win_x64.zip.sha256.txt
                      prod/latest.yml
                      prod/latest.yml.sha256.txt
            - name: Upload artifacts (manual run)
              if: success() && github.event_name != 'release'
              uses: actions/upload-artifact@v7
              with:
                  name: Filen-windows
                  path: |
                      prod/*.exe
                      prod/*.zip
                      prod/*.blockmap
                      prod/latest.yml
                  if-no-files-found: error

    buildLinux:
        name: Build linux artifacts and attach to release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            ELECTRON_BUILDER_CACHE: "/tmp/electron-builder"
            ELECTRON_BUILDER_DOWNLOAD_PATH: "/tmp/electron"
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
            - name: Clear builder cache
              run: |
                  if [ -d "$ELECTRON_BUILDER_CACHE" ]; then
                      rm -rf $ELECTRON_BUILDER_CACHE
                  fi

                  if [ -d "$ELECTRON_BUILDER_DOWNLOAD_PATH" ]; then
                      rm -rf $ELECTRON_BUILDER_DOWNLOAD_PATH
                  fi
            - name: Install dependencies
              run: npm ci
            - name: Fetch rclone binaries
              run: node build/rclone/fetch.mjs
            - name: Build
              run: npm run build:linux
            - name: Generate SHA256 hashes
              run: |
                  for file in prod/*; do
                    if [ -f "$file" ]; then
                      sha256sum "$file" | awk '{print $1}' > "$file.sha256.txt"
                    fi
                  done
            - name: Generate update hashes
              run: npm run build:hashes
            - name: Attach artifacts to release
              if: success() && github.event_name == 'release'
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: ${{ github.event.release.tag_name }}
                  files: |
                      prod/Filen_linux_aarch64.rpm
                      prod/Filen_linux_amd64.deb
                      prod/Filen_linux_arm64.AppImage
                      prod/Filen_linux_arm64.deb
                      prod/Filen_linux_arm64.zip
                      prod/Filen_linux_x64.zip
                      prod/Filen_linux_x86_64.AppImage
                      prod/Filen_linux_x86_64.rpm
                      prod/latest-linux-arm64.yml
                      prod/latest-linux.yml
                      prod/Filen_linux_aarch64.rpm.sha256.txt
                      prod/Filen_linux_amd64.deb.sha256.txt
                      prod/Filen_linux_arm64.AppImage.sha256.txt
                      prod/Filen_linux_arm64.deb.sha256.txt
                      prod/Filen_linux_arm64.zip.sha256.txt
                      prod/Filen_linux_x64.zip.sha256.txt
                      prod/Filen_linux_x86_64.AppImage.sha256.txt
                      prod/Filen_linux_x86_64.rpm.sha256.txt
                      prod/latest-linux-arm64.yml.sha256.txt
                      prod/latest-linux.yml.sha256.txt
            - name: Upload artifacts (manual run)
              if: success() && github.event_name != 'release'
              uses: actions/upload-artifact@v7
              with:
                  name: Filen-linux
                  path: |
                      prod/*.deb
                      prod/*.rpm
                      prod/*.AppImage
                      prod/*.zip
                      prod/latest-linux*.yml
                  if-no-files-found: error

    buildMac:
        name: Build macOS artifacts and attach to release
        runs-on: macos-latest
        permissions:
            contents: write
        env:
            CSC_LINK: ${{ secrets.CSC_LINK }}
            CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
            APPLE_ID: ${{ secrets.APPLE_ID }}
            APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
            APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
            ELECTRON_BUILDER_CACHE: "/tmp/electron-builder-cache"
            ELECTRON_BUILDER_DOWNLOAD_PATH: "/tmp/electron-download"
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
            - name: Clear builder cache
              run: |
                  if [ -d "$ELECTRON_BUILDER_CACHE" ]; then
                      rm -rf $ELECTRON_BUILDER_CACHE
                  fi

                  if [ -d "$ELECTRON_BUILDER_DOWNLOAD_PATH" ]; then
                      rm -rf $ELECTRON_BUILDER_DOWNLOAD_PATH
                  fi
            - name: Install dependencies
              run: npm ci
            - name: Fetch rclone binaries
              run: node build/rclone/fetch.mjs
            - name: Build
              run: npm run build:mac
            - name: Generate SHA256 hashes
              run: |
                  for file in prod/*; do
                    if [ -f "$file" ]; then
                      shasum -a 256 "$file" | awk '{print $1}' > "$file.sha256.txt"
                    fi
                  done
            - name: Generate update hashes
              run: npm run build:hashes
            - name: Attach artifacts to release
              if: success() && github.event_name == 'release'
              uses: softprops/action-gh-release@v3
              with:
                  tag_name: ${{ github.event.release.tag_name }}
                  files: |
                      prod/Filen_mac_x64.dmg
                      prod/Filen_mac_x64.dmg.sha256.txt
                      prod/Filen_mac_arm64.dmg
                      prod/Filen_mac_arm64.dmg.sha256.txt
                      prod/Filen_mac_x64.dmg.blockmap
                      prod/Filen_mac_x64.dmg.blockmap.sha256.txt
                      prod/Filen_mac_arm64.dmg.blockmap
                      prod/Filen_mac_arm64.dmg.blockmap.sha256.txt
                      prod/Filen_mac_x64.zip
                      prod/Filen_mac_x64.zip.sha256.txt
                      prod/Filen_mac_arm64.zip
                      prod/Filen_mac_arm64.zip.sha256.txt
                      prod/latest-mac.yml
                      prod/latest-mac.yml.sha256.txt
            - name: Upload artifacts (manual run)
              if: success() && github.event_name != 'release'
              uses: actions/upload-artifact@v7
              with:
                  name: Filen-macos
                  path: |
                      prod/*.dmg
                      prod/*.zip
                      prod/*.blockmap
                      prod/latest-mac.yml
                  if-no-files-found: error
